# Run with cmake -DTEST_BINARY_DIR=<scratch> [-DOPENVDB_TEST_PREFIX=<prefix>]
#   [-DTEST_GENERATOR=Ninja -DTEST_MAKE_PROGRAM=<ninja>] -P this-file.cmake.
cmake_minimum_required(VERSION 3.15)
if(NOT TEST_BINARY_DIR)
  message(FATAL_ERROR "Set TEST_BINARY_DIR to a disposable configure output directory")
endif()
get_filename_component(TEST_BINARY_DIR "${TEST_BINARY_DIR}" ABSOLUTE)
get_filename_component(_repo "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
set(_generator_args "")
if(TEST_GENERATOR)
  list(APPEND _generator_args -G "${TEST_GENERATOR}")
endif()
if(TEST_MAKE_PROGRAM)
  list(APPEND _generator_args "-DCMAKE_MAKE_PROGRAM=${TEST_MAKE_PROGRAM}")
endif()

set(_cases embedded ilmbase imath legacy defined_zero missing_ilmbase missing_imath)
if(OPENVDB_TEST_PREFIX)
  get_filename_component(OPENVDB_TEST_PREFIX "${OPENVDB_TEST_PREFIX}" ABSOLUTE)
  list(APPEND _cases installed)
endif()
foreach(_case IN LISTS _cases)
  execute_process(
    COMMAND "${CMAKE_COMMAND}" -S "${CMAKE_CURRENT_LIST_DIR}/openvdb_finder"
      -B "${TEST_BINARY_DIR}/${_case}" ${_generator_args}
      "-DFIXTURE_CASE=${_case}" "-DOPENVDB_TEST_PREFIX=${OPENVDB_TEST_PREFIX}"
    RESULT_VARIABLE _result OUTPUT_VARIABLE _output ERROR_VARIABLE _error)
  if(_case MATCHES "^missing_")
    if(_result EQUAL 0)
      message(FATAL_ERROR "${_case}: configure should reject the missing required Half provider")
    endif()
    if(_case STREQUAL missing_ilmbase)
      set(_expected_error "IlmBase::Half can not be found")
    else()
      set(_expected_error "Imath::Imath can not be found")
    endif()
    string(FIND "${_output}${_error}" "${_expected_error}" _found_error)
    if(_found_error LESS 0)
      message(FATAL_ERROR "${_case}: unexpected failure\n${_output}\n${_error}")
    endif()
  elseif(NOT _result EQUAL 0)
    message(FATAL_ERROR "${_case}: configure failed\n${_output}\n${_error}")
  endif()
  message(STATUS "Passed: ${_case}")
endforeach()

include("${_repo}/deps/DependencyGraph.cmake")
set(_closure OpenVDB)
set(_previous "")
while(NOT "${_closure}" STREQUAL "${_previous}")
  set(_previous "${_closure}")
  foreach(_package IN LISTS _previous)
    list(APPEND _closure ${DEP_${_package}_DEPENDS})
  endforeach()
  list(REMOVE_DUPLICATES _closure)
endwhile()
list(SORT _closure)
if(NOT "${_closure}" STREQUAL "Blosc;Boost;OpenVDB;TBB;ZLIB")
  message(FATAL_ERROR "Unexpected pinned OpenVDB dependency closure: ${_closure}")
endif()
message(STATUS "Pinned OpenVDB closure: ${_closure}")
