"""Small, standard-library-only tests; never execute a slicer or compiler."""

import argparse
import importlib.util
import json
from pathlib import Path
import struct
import subprocess
import tempfile
import unittest
from unittest.mock import patch


SCRIPT = Path(__file__).resolve().parents[2] / "tools/verify_release_smoke.py"
SPEC = importlib.util.spec_from_file_location("verify_release_smoke", SCRIPT)
smoke = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(smoke)


def gcode(version="2.9.4", day="01", body=b"G1 X20 Y20 E1\n; config_version = 2.9\n"):
    return (f"; generated by PrusaSlicer {version} on 2026-09-{day} at 12:00:00 UTC\n"
            .encode("ascii") + b"\n" + body)


def binary_stl(header=b"baseline", x=1.0):
    return (header.ljust(80, b"\0") + struct.pack("<I", 1) +
            struct.pack("<12fH", 0, 0, 1, 0, 0, 0, x, 0, 0, 0, 1, 0, 0))


class FingerprintTests(unittest.TestCase):
    def test_only_first_generated_header_is_removed(self):
        body = b"; generated by PrusaSlicer unusual comment\r\nG1 X1\r\n"
        first, removed = smoke.normalize_gcode(gcode(body=body))
        second, _ = smoke.normalize_gcode(gcode(version="2.10.0-alpha+local", day="09", body=body))
        self.assertEqual(first, second)
        self.assertEqual(first, b"\n" + body)
        self.assertIn("2.9.4", removed)
        self.assertNotEqual(first, smoke.normalize_gcode(gcode(body=body.replace(b"X1", b"X2")))[0])
        self.assertNotEqual(first, smoke.normalize_gcode(gcode(body=body.replace(b"\r\n", b"\n")))[0])

    def test_no_unrecognized_or_embedded_header_is_hidden(self):
        for data in (b"G1 X1\n", b"; another header\n" + gcode(), b"GCDE\0\0\xff"):
            with self.assertRaises((ValueError, UnicodeError)):
                smoke.normalize_gcode(data)

    def test_stl_header_is_ignored_but_all_triangle_bytes_are_preserved(self):
        first = binary_stl()
        second = binary_stl(header=b"solid candidate")
        self.assertNotEqual(smoke.sha256(first), smoke.sha256(second))
        self.assertEqual(smoke.stl_geometry(first), smoke.stl_geometry(second))
        self.assertNotEqual(smoke.stl_geometry(first), smoke.stl_geometry(binary_stl(x=2.0)))
        self.assertEqual(smoke.stl_geometry(first)[1], 1)

    def test_invalid_stl_is_rejected(self):
        for data in (b"solid test\nendsolid test\n", binary_stl()[:-1],
                     binary_stl() + b"x", b"\0" * 84):
            with self.assertRaises(ValueError):
                smoke.stl_geometry(data)


class WorkflowTests(unittest.TestCase):
    def setUp(self):
        self.scratch = tempfile.TemporaryDirectory(prefix="prusaslicer-smoke-unit-")
        self.addCleanup(self.scratch.cleanup)
        self.root = Path(self.scratch.name)
        for label in ("baseline", "candidate"):
            release = self.root / label
            release.mkdir()
            (release / "prusa-slicer-console.exe").write_bytes(b"mock launcher, never executed")
        data = self.root / "source/tests/data"
        data.mkdir(parents=True)
        (data / "20mm_cube.obj").write_bytes(b"test cube")
        (data / "default_fff.ini").write_text("post_process = \nprinter_model = MK3\n", encoding="utf-8")
        (self.root / "screw.step").write_bytes(b"test STEP")
        self.args = argparse.Namespace(baseline=str(self.root / "baseline"),
                                       candidate=str(self.root / "candidate"),
                                       source_root=str(self.root / "source"),
                                       step=str(self.root / "screw.step"),
                                       output=str(self.root / "new-output"), timeout=1)

    def fake_run(self, command, **kwargs):
        work = Path(kwargs["cwd"])
        destination = Path(command[command.index("--output") + 1])
        self.assertFalse(kwargs["shell"])
        self.assertEqual(kwargs["stdin"], subprocess.DEVNULL)
        self.assertEqual(command[command.index("--threads") + 1], "2")
        self.assertEqual(Path(command[command.index("--datadir") + 1]), work / "datadir")
        self.assertEqual(destination.parent, work)
        self.assertFalse(destination.exists())
        if smoke.os.name == "nt":
            self.assertTrue(kwargs["creationflags"] & subprocess.BELOW_NORMAL_PRIORITY_CLASS)
        if destination.suffix == ".gcode":
            self.assertIn("--no-binary-gcode", command)
            self.assertIn("--load", command)
            destination.write_bytes(gcode(day="01" if work.name == "baseline" else "09"))
        else:
            destination.write_bytes(binary_stl(header=work.name.encode("ascii")))
        kwargs["stdout"].write(b"mock output only\n")
        return subprocess.CompletedProcess(command, 0)

    def test_entire_mocked_workflow_preserves_inputs_and_records_results(self):
        original = {path: path.read_bytes() for path in self.root.rglob("*") if path.is_file()}
        with patch.object(smoke.subprocess, "run", side_effect=self.fake_run) as run:
            self.assertEqual(smoke.verify(self.args), 0)
        self.assertEqual(run.call_count, 6)
        report = json.loads((Path(self.args.output) / "report.json").read_text())
        self.assertTrue(report["executions_ok"])
        self.assertEqual(report["parity"], "equal")
        for value in report["comparisons"].values():
            self.assertFalse(value["raw_equal"])
            self.assertTrue(value["normalized_equal"])
        self.assertEqual(len(report["files"]), 18)
        for commands in report["commands"].values():
            for command in commands:
                self.assertEqual(command["exit_code"], 0)
                self.assertGreaterEqual(command["elapsed_seconds"], 0)
        for path, content in original.items():
            self.assertEqual(path.read_bytes(), content)

    def test_parity_difference_is_distinct_from_execution_failure(self):
        def changed_run(command, **kwargs):
            result = self.fake_run(command, **kwargs)
            destination = Path(command[command.index("--output") + 1])
            if destination.name == "cube_slice.gcode" and destination.parent.name == "candidate":
                destination.write_bytes(gcode(body=b"G1 X21 Y20 E1\n"))
            return result
        with patch.object(smoke.subprocess, "run", side_effect=changed_run):
            self.assertEqual(smoke.verify(self.args), 2)
        report = json.loads((Path(self.args.output) / "report.json").read_text())
        self.assertTrue(report["executions_ok"])
        self.assertEqual(report["parity"], "different")
        self.assertIn("first_different_normalized_line", report["comparisons"]["cube_slice"])

    def test_command_timeout_is_an_execution_failure_with_logs(self):
        with patch.object(smoke.subprocess, "run", side_effect=subprocess.TimeoutExpired("mock", 1)):
            self.assertEqual(smoke.verify(self.args), 1)
        report = json.loads((Path(self.args.output) / "report.json").read_text())
        self.assertFalse(report["executions_ok"])
        self.assertEqual(report["parity"], "not-comparable")
        self.assertTrue(report["commands"]["baseline"][0]["timed_out"])

    def test_existing_scratch_is_rejected_without_running_anything(self):
        output = Path(self.args.output)
        output.mkdir()
        marker = output / "keep"
        marker.write_bytes(b"preserve me")
        with patch.object(smoke.subprocess, "run") as run, self.assertRaises(ValueError):
            smoke.verify(self.args)
        run.assert_not_called()
        self.assertEqual(marker.read_bytes(), b"preserve me")

    def test_output_inside_release_is_rejected(self):
        self.args.output = str(self.root / "candidate/scratch")
        with self.assertRaises(ValueError):
            smoke.prepare(self.args)
        self.assertFalse(Path(self.args.output).exists())

    def test_postprocessing_commands_are_rejected(self):
        config = self.root / "source/tests/data/default_fff.ini"
        config.write_text("post_process = do-not-execute.exe\n", encoding="utf-8")
        with self.assertRaises(ValueError):
            smoke.prepare(self.args)
        self.assertFalse(Path(self.args.output).exists())


if __name__ == "__main__":
    unittest.main()
