# Pure CMake regression: no language enable, compiler, or native build.
cmake_minimum_required(VERSION 3.13)
if (POLICY CMP0141)
    cmake_policy(SET CMP0141 NEW)
endif()
include("${CMAKE_CURRENT_LIST_DIR}/../../cmake/modules/CompilerCache.cmake")

function(check_format launcher symbols expected)
    set(MSVC TRUE)
    set(CMAKE_CXX_COMPILER_LAUNCHER "${launcher}")
    set(CMAKE_C_COMPILER_LAUNCHER "${launcher}")
    set(SLIC3R_MSVC_DEBUG_SYMBOLS "${symbols}")
    unset(CMAKE_MSVC_DEBUG_INFORMATION_FORMAT)
    set(CMAKE_CXX_FLAGS_DEBUG "/Ob0 /Zi /ZI -Zi /DTEST_Zi=1 /Iinclude/Zi")
    set(CMAKE_C_FLAGS_RELWITHDEBINFO "/O2 /Zi")
    slic3r_configure_msvc_debug_information()
    if (POLICY CMP0141)
        if (NOT "${CMAKE_MSVC_DEBUG_INFORMATION_FORMAT}" STREQUAL "${expected}")
            message(FATAL_ERROR "Unexpected format '${CMAKE_MSVC_DEBUG_INFORMATION_FORMAT}', expected '${expected}'")
        endif()
    endif()
    if (launcher MATCHES "sccache")
        if (NOT CMAKE_CXX_FLAGS_DEBUG STREQUAL "/Ob0 /Z7 /Z7 /Z7 /DTEST_Zi=1 /Iinclude/Zi")
            message(FATAL_ERROR "Symbol-preserving token replacement failed: ${CMAKE_CXX_FLAGS_DEBUG}")
        endif()
        if (NOT CMAKE_C_FLAGS_RELWITHDEBINFO STREQUAL "/O2 /Z7" OR NOT SLIC3R_MSVC_DEBUG_FLAG STREQUAL "/Z7")
            message(FATAL_ERROR "C or old-CMake symbol fallback failed")
        endif()
    elseif (NOT CMAKE_CXX_FLAGS_DEBUG STREQUAL "/Ob0 /Zi /ZI -Zi /DTEST_Zi=1 /Iinclude/Zi")
        message(FATAL_ERROR "A non-sccache launcher changed existing flags")
    endif()
endfunction()

check_format("C:/cache path/sccache.exe" TRUE Embedded)
check_format("sccache" FALSE "$<$<CONFIG:Debug,RelWithDebInfo>:Embedded>")
check_format("" TRUE ProgramDatabase)
check_format("ccache" FALSE "$<$<CONFIG:Debug,RelWithDebInfo>:ProgramDatabase>")

# Explicit caller policy is preserved (including deliberate symbol omission).
set(MSVC TRUE)
set(CMAKE_CXX_COMPILER_LAUNCHER sccache)
set(CMAKE_MSVC_DEBUG_INFORMATION_FORMAT "")
slic3r_configure_msvc_debug_information()
if (NOT CMAKE_MSVC_DEBUG_INFORMATION_FORMAT STREQUAL "")
    message(FATAL_ERROR "Explicit debug format changed")
endif()

if (POLICY CMP0141)
    # Redefine the macro with OLD policy to exercise the <=3.24 path on a
    # modern CMake installation, without pretending to test an old executable.
    cmake_policy(SET CMP0141 OLD)
    include("${CMAKE_CURRENT_LIST_DIR}/../../cmake/modules/CompilerCache.cmake")
    check_format("sccache" TRUE "")
endif()
message(STATUS "PASS: MSVC compiler cache symbols, token boundaries, explicit format and old-policy fallback")
