cmake_minimum_required(VERSION 3.18)
if (POLICY CMP0141)
    cmake_policy(SET CMP0141 NEW)
endif()
project(PrusaSccacheSymbolProbe LANGUAGES CXX)
set(SLIC3R_MSVC_DEBUG_SYMBOLS ON)
include("${PRUSA_SOURCE}/cmake/modules/CompilerCache.cmake")
slic3r_enable_compiler_cache()
slic3r_configure_msvc_debug_information()
add_library(cache_probe OBJECT cache_probe.cpp)
