cmake_minimum_required(VERSION 3.18)
if (POLICY CMP0141)
    cmake_policy(SET CMP0141 NEW)
endif()
project(PrusaPchMechanismProbe LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17)
include("${PRUSA_SOURCE}/cmake/modules/CompilerCache.cmake")
slic3r_enable_compiler_cache()
slic3r_configure_msvc_debug_information()
add_library(pch_probe OBJECT a.cpp b.cpp)
target_precompile_headers(pch_probe PRIVATE stable.hpp)
if (FULL_PCH)
    target_precompile_headers(pch_probe PRIVATE project.hpp)
endif()
