#!/usr/bin/env python3
"""Compare two Windows releases using isolated, offline CLI smoke operations.

Example:
  python tools/verify_release_smoke.py BASELINE CANDIDATE --source-root . \
      --step path/to/screw.step --output out/release-smoke-new

The output directory must be new and its parent must exist. Input releases and
fixtures are never modified by this script. Each release gets its own working
directory and --datadir. Commands run sequentially, without a shell, with two
slicer threads and Windows below-normal priority. Wrap this script in
run_guarded.py for an additional process-tree memory/CPU guard.

Exit codes: 0 = commands and parity passed; 1 = execution/output validation
failed; 2 = commands passed but output parity differs (investigate report.json).
This is a small functionality check, not complete GUI/feature validation, a
startup benchmark, or proof that differing toolpaths are incorrect.
"""

import argparse
import hashlib
import json
import os
from pathlib import Path
import re
import struct
import subprocess
import time


GENERATED_HEADER = re.compile(
    rb"; generated by PrusaSlicer [^\r\n]+ on "
    rb"\d{4}-\d{2}-\d{2} at \d{2}:\d{2}:\d{2} UTC(?:\r?\n|$)"
)


def sha256(data):
    return hashlib.sha256(data).hexdigest()


def file_record(path, root=None):
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return {"path": str(path.relative_to(root) if root else path),
            "bytes": path.stat().st_size, "sha256": digest.hexdigest()}


def normalize_gcode(data):
    """Remove ONLY the first, source-generated version/timestamp header.

    See GCode.cpp's first write_format, Utils.cpp:header_slic3r_generated and
    Time.cpp:SLICER_UTC_TIME_FMT. Keep all other bytes, including line endings,
    config/version comments, estimates and toolpaths. Do not mask mismatches.
    """
    data.decode("utf-8")  # Reject binary G-code / corrupt text.
    header = GENERATED_HEADER.match(data)
    if not header:
        raise ValueError("G-code does not start with the expected PrusaSlicer header")
    return data[header.end():], header.group().decode("utf-8")


def stl_geometry(data):
    """Return exact binary STL geometry bytes, ignoring only its 80-byte header.

    CLI/ProcessActions.cpp export_models(IO::STL) passes binary=true to
    store_stl. Thus this is the demonstrated CLI format, not a guessed format
    based on the 'solid' prefix (binary STL can start with that prefix too).
    Validate the full byte count; retain facet order, normals and attributes.
    ASCII output is rejected instead of silently applying extra normalization.
    """
    if len(data) < 84:
        raise ValueError("STL is shorter than a binary STL header")
    facets = struct.unpack_from("<I", data, 80)[0]
    if facets == 0 or len(data) != 84 + 50 * facets:
        raise ValueError("STL is empty, truncated, or not the expected binary format")
    return data[80:], facets


def fingerprint(path):
    data = path.read_bytes()
    result = file_record(path)
    if path.suffix == ".stl":
        normalized, facets = stl_geometry(data)
        result.update(format="binary-stl", facets=facets,
                      normalization="remove exactly the 80-byte STL header")
    else:
        normalized, header = normalize_gcode(data)
        result.update(format="text-gcode", removed_header=header,
                      normalization="remove only the first generated-by version/time header")
    result["normalized_sha256"] = sha256(normalized)
    return result, normalized


def is_within(path, root):
    try:
        path.relative_to(root)
        return True
    except ValueError:
        return False


def prepare(args):
    """Preflight everything before creating an exclusively owned scratch root."""
    releases = {name: Path(getattr(args, name)).resolve(strict=True)
                for name in ("baseline", "candidate")}
    for root in releases.values():
        if not (root / "prusa-slicer-console.exe").is_file():
            raise ValueError(f"Console launcher missing from release: {root}")
    source = Path(args.source_root).resolve(strict=True)
    fixtures = {"cube": source / "tests/data/20mm_cube.obj",
                "config": source / "tests/data/default_fff.ini",
                "step": Path(args.step).resolve(strict=True)}
    for path in fixtures.values():
        if not path.is_file():
            raise ValueError(f"Fixture is not a file: {path}")
    post_process = re.findall(r"^post_process[ \t]*=[ \t]*([^\r\n]*)",
                              fixtures["config"].read_text(encoding="utf-8"), re.M)
    if not post_process or any(value.strip() for value in post_process):
        raise ValueError("FFF fixture must explicitly have an empty post_process setting")
    raw_output = Path(args.output).absolute()
    if os.path.lexists(raw_output):
        raise ValueError(f"Output already exists; choose a new scratch directory: {raw_output}")
    output = raw_output.parent.resolve(strict=True) / raw_output.name
    if any(is_within(output, root) for root in releases.values()):
        raise ValueError("Scratch output must not be inside either release directory")
    if is_within(output, source / "tests/data"):
        raise ValueError("Scratch output must not be inside a fixture directory")
    output.mkdir(exist_ok=False)
    return releases, fixtures, output


def command_plan(release, fixtures, work):
    common = [str(release / "prusa-slicer-console.exe"),
              "--datadir", str(work / "datadir"), "--threads", "2"]
    plan = []
    for name, model, action, suffix in (
            ("step_export", fixtures["step"], "--export-stl", ".stl"),
            ("cube_slice", fixtures["cube"], "--export-gcode", ".gcode"),
            ("step_slice", fixtures["step"], "--export-gcode", ".gcode")):
        destination = work / (name + suffix)
        config = (["--load", str(fixtures["config"]), "--no-binary-gcode"]
                  if suffix == ".gcode" else [])
        command = common + config + [action, "--output", str(destination), str(model)]
        plan.append((name, command, destination))
    return plan


def run_command(name, command, destination, work, timeout):
    # Fixed filenames inside a newly created private directory. Never overwrite.
    if os.path.lexists(destination):
        raise ValueError(f"Unexpected existing command output: {destination}")
    result = {"name": name, "argv": command, "cwd": str(work),
              "exit_code": None, "timed_out": False, "ok": False}
    options = {}
    if os.name == "nt":
        options["creationflags"] = (subprocess.BELOW_NORMAL_PRIORITY_CLASS |
                                    subprocess.CREATE_NO_WINDOW)
    started = time.perf_counter()
    with (work / (name + ".stdout.log")).open("xb") as stdout, \
            (work / (name + ".stderr.log")).open("xb") as stderr:
        try:
            completed = subprocess.run(command, cwd=work, shell=False,
                                       stdin=subprocess.DEVNULL, stdout=stdout,
                                       stderr=stderr, timeout=timeout, **options)
            result["exit_code"] = completed.returncode
        except subprocess.TimeoutExpired:
            result.update(timed_out=True, error=f"Command exceeded {timeout} seconds")
        except OSError as error:
            result["error"] = str(error)
    result["elapsed_seconds"] = time.perf_counter() - started
    if destination.is_file():
        result["output"] = file_record(destination)
        try:
            result["output"], _ = fingerprint(destination)
            result["ok"] = result["exit_code"] == 0
        except (ValueError, UnicodeError) as error:
            result["output_error"] = str(error)
    else:
        result["output_error"] = "Expected output was not created"
    return result


def compare_outputs(left, right):
    first, first_data = fingerprint(left)
    second, second_data = fingerprint(right)
    result = {"baseline": first, "candidate": second,
              "raw_equal": first["sha256"] == second["sha256"],
              "normalized_equal": first_data == second_data}
    if not result["normalized_equal"]:
        offset = next((i for i, (a, b) in enumerate(zip(first_data, second_data)) if a != b),
                      min(len(first_data), len(second_data)))
        result["first_different_normalized_byte"] = offset
        if left.suffix == ".gcode":
            result["first_different_normalized_line"] = first_data[:offset].count(b"\n") + 1
    return result


def verify(args):
    releases, fixtures, output = prepare(args)
    report = {"schema_version": 1, "output": str(output),
              "inputs": {name: file_record(path) for name, path in fixtures.items()},
              "releases": {name: str(path) for name, path in releases.items()},
              "commands": {}, "comparisons": {}, "executions_ok": False,
              "parity": "not-comparable", "threads": 2,
              "priority": "below-normal" if os.name == "nt" else "inherited",
              "scope": "CLI STEP import/STL export and FFF cube/STEP slicing only"}
    plans = {}
    for label, release in releases.items():
        work = output / label
        work.mkdir(exist_ok=False)
        (work / "datadir").mkdir(exist_ok=False)
        plans[label] = command_plan(release, fixtures, work)
        report["commands"][label] = [run_command(name, command, destination, work, args.timeout)
                                     for name, command, destination in plans[label]]
    for baseline, candidate in zip(plans["baseline"], plans["candidate"]):
        try:
            report["comparisons"][baseline[0]] = compare_outputs(baseline[2], candidate[2])
        except (OSError, ValueError, UnicodeError) as error:
            report["comparisons"][baseline[0]] = {"error": str(error)}
    report["executions_ok"] = all(command["ok"] for commands in report["commands"].values()
                                  for command in commands)
    comparable = all("normalized_equal" in comparison
                     for comparison in report["comparisons"].values())
    if comparable:
        report["parity"] = ("equal" if all(item["normalized_equal"]
                            for item in report["comparisons"].values()) else "different")
    report["files"] = [file_record(path, output) for path in sorted(output.rglob("*"))
                       if path.is_file()]
    report_path = output / "report.json"
    with report_path.open("x", encoding="utf-8") as stream:
        json.dump(report, stream, indent=2)
        stream.write("\n")
    print(f"Commands passed: {report['executions_ok']}; parity: {report['parity']}; {report_path}")
    if not report["executions_ok"] or not comparable:
        return 1
    return 0 if report["parity"] == "equal" else 2


def positive_timeout(value):
    number = float(value)
    if not 0 < number < float("inf"):
        raise argparse.ArgumentTypeError("Timeout must be finite and positive")
    return number


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("baseline", help="Baseline Windows release directory")
    parser.add_argument("candidate", help="Candidate Windows release directory")
    parser.add_argument("--source-root", required=True)
    parser.add_argument("--step", required=True, help="Small offline STEP fixture")
    parser.add_argument("--output", required=True, help="New scratch directory; parent must exist")
    parser.add_argument("--timeout", type=positive_timeout, default=300,
                        help="Maximum seconds per command (default: 300)")
    args = parser.parse_args()
    try:
        return verify(args)
    except (OSError, ValueError) as error:
        parser.exit(1, f"Smoke verification failed: {error}\n")


if __name__ == "__main__":
    raise SystemExit(main())
